/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.designerole;

import business.ecosystem.Ecosystem;
import business.enterprise.Enterprise;
import business.organization.DesignOrganization;
import business.organization.ManufactureOrganization;
import business.organization.Organization;
import business.useraccount.UserAccount;
import business.workqueue.CustomerCustomizedWorkRequest;
import business.workqueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raksha
 */
public class DesignWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form designWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private DesignOrganization designOrganization;
    private UserAccount userAccount;
    private Ecosystem business;

    public DesignWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.designOrganization = (DesignOrganization) organization;
        this.userAccount = userAccount;
        this.business = business;

        populateDesignTable();
        //add enterprise name to label
        valueLabel.setText(enterprise.getName());
        orgValueLabel.setText(organization.getName());
    }

    public void populateDesignTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);

        for (WorkRequest wr : designOrganization.getWorkQueue().getWorkRequestList()) {

            Object[] row = new Object[5];
            CustomerCustomizedWorkRequest cw = (CustomerCustomizedWorkRequest) wr;
            row[0] = cw;
            row[1] = cw.getStoreSender() == null ? null : cw.getStoreSender().getEmployee().getName();
            row[2] = cw.getDesignerReceiver() == null ? null : cw.getDesignerReceiver().getEmployee().getName();
            row[3] = cw.getRequestDate();
            row[4] = cw.getStatus();
            model.addRow(row);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshTestJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        requestManufacturertJButton = new javax.swing.JButton();
        designCompleteJButton = new javax.swing.JButton();
        assignToMeJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        orgValueLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(191, 238, 238));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        refreshTestJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.png"))); // NOI18N
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });
        add(refreshTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 79, 62));

        workRequestJTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderID", "Sender", "Receiver", "RequestDate", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 860, 70));

        requestManufacturertJButton.setBackground(new java.awt.Color(51, 204, 255));
        requestManufacturertJButton.setText("Request Manufacturing Team");
        requestManufacturertJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestManufacturertJButtonActionPerformed(evt);
            }
        });
        add(requestManufacturertJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, 49));

        designCompleteJButton.setBackground(new java.awt.Color(51, 153, 255));
        designCompleteJButton.setText("Design Complete");
        designCompleteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designCompleteJButtonActionPerformed(evt);
            }
        });
        add(designCompleteJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, 49));

        assignToMeJButton.setBackground(new java.awt.Color(51, 255, 255));
        assignToMeJButton.setText("Accept Request");
        assignToMeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignToMeJButtonActionPerformed(evt);
            }
        });
        add(assignToMeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 138, 48));

        jLabel1.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 18)); // NOI18N
        jLabel1.setText("Design Staff Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 230, 30));

        backJButton.setBackground(new java.awt.Color(51, 153, 255));
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.jpg"))); // NOI18N
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 13, 69, 63));

        valueLabel.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 80, 20));

        enterpriseLabel.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 100, 80, 30));

        enterpriseLabel1.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        enterpriseLabel1.setText("Organization:");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 120, 90, 26));

        orgValueLabel.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        orgValueLabel.setText("<value>");
        add(orgValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 80, 26));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        populateDesignTable();

    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void requestManufacturertJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestManufacturertJButtonActionPerformed
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table first ", "Warning", JOptionPane.WARNING_MESSAGE);

            return;
        }

        CustomerCustomizedWorkRequest cRequest = (CustomerCustomizedWorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
        //check the status for designer
        if (cRequest.getStatus().equals("Order Ready")) {
            JOptionPane.showMessageDialog(null, "Please complete the design first", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (cRequest.getStatus().equals("Pending With Design")) {
            JOptionPane.showMessageDialog(null, "The design is not ready", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (cRequest.getStatus().equals("Design Complete")) {
            cRequest.setStatus("Manufacture Order");
            cRequest.setDesignerSender(userAccount);
            userAccount.getWorkQueue().getWorkRequestList().add(cRequest);

            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof ManufactureOrganization) {
                    organization.getWorkQueue().getWorkRequestList().add(cRequest);

                }

            }
            JOptionPane.showMessageDialog(null, " Design sent to Manufacturer for manufacturing", "Warning", JOptionPane.WARNING_MESSAGE);

        }


    }//GEN-LAST:event_requestManufacturertJButtonActionPerformed

    private void assignToMeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignToMeJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table first ", "Warning", JOptionPane.WARNING_MESSAGE);

            return;
        }

        CustomerCustomizedWorkRequest request = (CustomerCustomizedWorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
        request.setDesignerReceiver(userAccount);
        request.setStatus("Pending With Design");
        populateDesignTable();
    }//GEN-LAST:event_assignToMeJButtonActionPerformed

    private void designCompleteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designCompleteJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table first ", "Warning", JOptionPane.WARNING_MESSAGE);

            return;
        }

        CustomerCustomizedWorkRequest request = (CustomerCustomizedWorkRequest) workRequestJTable.getValueAt(selectedRow, 0);

        request.setStatus("Design Complete");
        populateDesignTable();


    }//GEN-LAST:event_designCompleteJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignToMeJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton designCompleteJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel orgValueLabel;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JButton requestManufacturertJButton;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
