/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.reporting;

import business.barchartsample.HazardousContentReportChart;
import business.barchartsample.Report;
import business.customer.MasterOrderList;
import business.ecosystem.Ecosystem;
import business.enterprise.CarCooperEnterprise;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.Organization;
import business.organization.ReportingOrganization;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;


/**
 *
 * @author sonalichaudhari
 */
public class LeadContentReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LeadContentReportJPanel
     */
    private MasterOrderList mod;
    private JPanel userProcessContainer;
    Report report ;
    private Ecosystem business;

    final String applicationTitle = "Hazardous Content Chart";
    final String chartTitle = "Hazardous Content Chart";
    float airFilterLDContent = 0;
    float airFilterFDHContent = 0;
    float airFilterCMContent = 0;

    float paintLDContent = 0;
    float paintFDHContent = 0;
    float paintCMContent = 0;

    float engineLDContent = 0;
    float enginwFDHContent = 0;
    float engineCMContent = 0;

    float fuelLDContent = 0;
    float fuelFDHContent = 0;
    float fuelCMContent = 0;

    public LeadContentReportJPanel(JPanel userProcessContainer, MasterOrderList mod,Ecosystem business) {
        initComponents();
        this.mod = mod;
        this.report = new Report();
        this.userProcessContainer = userProcessContainer;
        this.business=business;
        
        addReportToOrganization();
    }
    //adding report to the organization
    public void addReportToOrganization(){
         for(Network network: business.getNetworkList())
        {
            for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList())
            {
                if(enterprise instanceof CarCooperEnterprise)
                {
                    for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList())
                    {
                        if(organization instanceof ReportingOrganization)
                        {
                            ((ReportingOrganization) organization).setReport(report);
                        }
                    }
                }
            }
        }    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportDisplayjPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        airFilterjComboBox = new javax.swing.JComboBox<>();
        paintjComboBox = new javax.swing.JComboBox<>();
        engineTypejComboBox = new javax.swing.JComboBox();
        generatePieChartjButton = new javax.swing.JButton();
        fuelTypejComboBox = new javax.swing.JComboBox<>();
        backJButton7 = new javax.swing.JButton();
        pieReportjPanel = new javax.swing.JPanel();
        generateGraphjButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reportDisplayjPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        reportDisplayjPanel.setLayout(new java.awt.BorderLayout());
        add(reportDisplayjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 500, 400));

        jLabel6.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 18)); // NOI18N
        jLabel6.setText("Paint");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 18)); // NOI18N
        jLabel7.setText("Airfilter");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 18)); // NOI18N
        jLabel8.setText("Engine");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 18)); // NOI18N
        jLabel9.setText("Fuel");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        airFilterjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paper", "Foam", "Cotton", "Stainless Steel", "Mesh" }));
        add(airFilterjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 140, 30));

        paintjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pearl White", "Black", "Mettalic Grey", "Gold", "Red", "Silver", "Brown" }));
        add(paintjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 140, -1));

        engineTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Diesel V6", "V-8s", "Three 4-cyl. turbos", "Two 2-cyl. turbos" }));
        engineTypejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engineTypejComboBoxActionPerformed(evt);
            }
        });
        add(engineTypejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 140, -1));

        generatePieChartjButton.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        generatePieChartjButton.setText("Generate Cumulative Graph ");
        generatePieChartjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatePieChartjButtonActionPerformed(evt);
            }
        });
        add(generatePieChartjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 120, -1, 40));

        fuelTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FFV", "EV", "PHEV", "CNG", "FCV" }));
        fuelTypejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuelTypejComboBoxActionPerformed(evt);
            }
        });
        add(fuelTypejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 140, -1));

        backJButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.jpg"))); // NOI18N
        backJButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton7ActionPerformed(evt);
            }
        });
        add(backJButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        pieReportjPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(pieReportjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 680, 400));

        generateGraphjButton1.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        generateGraphjButton1.setText("Generate Graph");
        generateGraphjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateGraphjButton1ActionPerformed(evt);
            }
        });
        add(generateGraphjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void engineTypejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engineTypejComboBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_engineTypejComboBoxActionPerformed

    private void generatePieChartjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatePieChartjButtonActionPerformed

        DefaultCategoryDataset barchartdata = new DefaultCategoryDataset();
        //setting values of the bar chart
        barchartdata.setValue(report.getCumleadContent(), "Lead", "Lead");
        barchartdata.setValue(report.getCumCarbonMContent(), "Lead", "Carbon Monoxide");
        barchartdata.setValue(report.getCumFMDHContent(), "Lead", "Formalehyde");

        JFreeChart barchart = ChartFactory.createBarChart3D("Report", "TYPES", "Hazardous Content Value", barchartdata, PlotOrientation.VERTICAL, true, true, false);
        CategoryPlot p = barchart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.black);
        ChartFrame chartfn = new ChartFrame("REVENUE GENERATION", barchart, true);
        //initComponents();
        chartfn.setSize(650, 400);

        pieReportjPanel.removeAll();
        pieReportjPanel.add(chartfn.getChartPanel());
        pieReportjPanel.setVisible(true);
        pieReportjPanel.setEnabled(true);
        pieReportjPanel.validate();

    }//GEN-LAST:event_generatePieChartjButtonActionPerformed

    private void fuelTypejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelTypejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuelTypejComboBoxActionPerformed

    private void backJButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton7ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton7ActionPerformed

    private void generateGraphjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateGraphjButton1ActionPerformed
        setValuesForGraph();
    }//GEN-LAST:event_generateGraphjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> airFilterjComboBox;
    private javax.swing.JButton backJButton7;
    private javax.swing.JComboBox engineTypejComboBox;
    private javax.swing.JComboBox<String> fuelTypejComboBox;
    private javax.swing.JButton generateGraphjButton1;
    private javax.swing.JButton generatePieChartjButton;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> paintjComboBox;
    private javax.swing.JPanel pieReportjPanel;
    private javax.swing.JPanel reportDisplayjPanel;
    // End of variables declaration//GEN-END:variables

    private void setValuesForGraph() {

        if (airFilterjComboBox.getSelectedItem().equals("Paper")) {
            airFilterLDContent = (float) (airFilterLDContent + 3.0);
            airFilterCMContent = (float) (airFilterCMContent + 4.0);
            airFilterFDHContent = (float) (airFilterFDHContent + 3.4);
        } else if (airFilterjComboBox.getSelectedItem().equals("Foam")) {
            airFilterLDContent = (float) (airFilterLDContent + 6.7);
            airFilterCMContent = (float) (airFilterCMContent + 8.8);
            airFilterFDHContent = (float) (airFilterFDHContent + 7.9);
        } else if (airFilterjComboBox.getSelectedItem().equals("Cotton")) {
            airFilterLDContent = (float) (airFilterLDContent + 2.3);
            airFilterCMContent = (float) (airFilterCMContent + 5.4);
            airFilterFDHContent = (float) (airFilterFDHContent + 6.8);
        } else if (airFilterjComboBox.getSelectedItem().equals("Stainless Steel")) {
            airFilterLDContent = (float) (airFilterLDContent + 8.5);
            airFilterCMContent = (float) (airFilterCMContent + 9.02);
            airFilterFDHContent = (float) (airFilterFDHContent + 8.79);
        } else if (airFilterjComboBox.getSelectedItem().equals("Mesh")) {
            airFilterLDContent = (float) (airFilterLDContent + 2.8);
            airFilterCMContent = (float) (airFilterCMContent + 3.8);
            airFilterFDHContent = (float) (airFilterFDHContent + 3.48);
        }

        if (engineTypejComboBox.getSelectedItem().equals("Diesel V6")) {
            engineLDContent = (float) (engineLDContent + 8.8);
            engineCMContent = (float) (engineCMContent + 9.78);
            enginwFDHContent = (float) (enginwFDHContent + 9.0);
        } else if (engineTypejComboBox.getSelectedItem().equals("V-8s")) {
            engineLDContent = (float) (engineLDContent + 6.87);
            engineCMContent = (float) (engineCMContent + 8.85);
            enginwFDHContent = (float) (enginwFDHContent + 5.7);
        } else if (engineTypejComboBox.getSelectedItem().equals("Three 4-cyl. turbos")) {
            engineLDContent = (float) (engineLDContent + 5.4);
            engineCMContent = (float) (engineCMContent + 6.32);
            enginwFDHContent = (float) (enginwFDHContent + 4.53);
        } else if (engineTypejComboBox.getSelectedItem().equals("Two 2-cyl. turbos")) {
            engineLDContent = (float) (engineLDContent + 4.38);
            engineCMContent = (float) (engineCMContent + 5.3);
            enginwFDHContent = (float) (enginwFDHContent + 8.3);
        }

        if (paintjComboBox.getSelectedItem().equals("Pearl White")) {
            paintLDContent = (float) (paintLDContent + 4.2);
            paintFDHContent = (float) (paintFDHContent + 3.5);
            paintCMContent = (float) (paintCMContent + 6.0);
        } else if (paintjComboBox.getSelectedItem().equals("Black")) {
            paintLDContent = (float) (paintLDContent + 9.6);
            paintFDHContent = (float) (paintFDHContent + 8.55);
            paintCMContent = (float) (paintCMContent + 9.5);
        } else if (paintjComboBox.getSelectedItem().equals("Mettalic Grey")) {
            paintLDContent = (float) (paintLDContent + 7.9);
            paintFDHContent = (float) (paintFDHContent + 9.56);
            paintCMContent = (float) (paintCMContent + 9.7);
        } else if (paintjComboBox.getSelectedItem().equals("Gold")) {
            paintLDContent = (float) (paintLDContent + 6.33);
            paintFDHContent = (float) (paintFDHContent + 5.35);
            paintCMContent = (float) (paintCMContent + 6.99);
        } else if (paintjComboBox.getSelectedItem().equals("Red")) {
            paintLDContent = (float) (paintLDContent + 7.85);
            paintFDHContent = (float) (paintFDHContent + 9.38);
            paintCMContent = (float) (paintCMContent + 7.54);
        } else if (paintjComboBox.getSelectedItem().equals("Silver")) {
            paintLDContent = (float) (paintLDContent + 8.97);
            paintFDHContent = (float) (paintFDHContent + 7.77);
            paintCMContent = (float) (paintCMContent + 6.32);
        } else if (paintjComboBox.getSelectedItem().equals("Brown")) {
            paintLDContent = (float) (paintLDContent + 9.45);
            paintFDHContent = (float) (paintFDHContent + 9.8);
            paintCMContent = (float) (paintCMContent + 8.34);
        }

        if (fuelTypejComboBox.getSelectedItem().equals("FFV")) {
            fuelLDContent = (float) (fuelLDContent + 7.33);
            fuelCMContent = (float) (fuelCMContent + 8.5);
            fuelFDHContent = (float) (fuelFDHContent + 6.74);
        } else if (fuelTypejComboBox.getSelectedItem().equals("EV")) {
            fuelLDContent = (float) (fuelLDContent + 4.33);
            fuelCMContent = (float) (fuelCMContent + 5.3);
            fuelFDHContent = (float) (fuelFDHContent + 8.3);
        } else if (fuelTypejComboBox.getSelectedItem().equals("PHEV")) {
            fuelLDContent = (float) (fuelLDContent + 4.42);
            fuelCMContent = (float) (fuelCMContent + 7.4);
            fuelFDHContent = (float) (fuelFDHContent + 7.3);
        } else if (fuelTypejComboBox.getSelectedItem().equals("CNG")) {
            fuelLDContent = (float) (fuelLDContent + 3.4);
            fuelCMContent = (float) (fuelCMContent + 2.4);
            fuelFDHContent = (float) (fuelFDHContent + 1.45);
        } else if (fuelTypejComboBox.getSelectedItem().equals("FCV")) {
            fuelLDContent = (float) (fuelLDContent + 6.76);
            fuelCMContent = (float) (fuelCMContent + 8.45);
            fuelFDHContent = (float) (fuelFDHContent + 8.54);
        }

        report.setLeadAirFilter(airFilterLDContent);
        report.setCmAirFilter(airFilterCMContent);
        report.setFmdhAirFilter(airFilterFDHContent);

        report.setLeadPaint(paintLDContent);
        report.setCmPaint(paintCMContent);
        report.setFmdhPaint(paintFDHContent);

        report.setLeadEngine(engineLDContent);
        report.setCmEngine(engineCMContent);
        report.setFmdhEngine(enginwFDHContent);

        report.setLeadFuel(fuelLDContent);
        report.setCmFuel(fuelCMContent);
        report.setFmdhFuel(fuelFDHContent);

        //For use in pie-chart   
        report.setCumleadContent(airFilterLDContent + paintLDContent + fuelLDContent);
        report.setCumCarbonMContent(airFilterCMContent + paintCMContent + fuelLDContent);
        report.setCumFMDHContent(airFilterFDHContent + paintFDHContent + fuelFDHContent);


        //initComponents();
        HazardousContentReportChart chart = new HazardousContentReportChart(applicationTitle, chartTitle, report);
        reportDisplayjPanel.removeAll();
        reportDisplayjPanel.add(chart.getChartPanel());
        reportDisplayjPanel.setVisible(true);
        reportDisplayjPanel.validate();
    }

}
