/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.reporting;

import business.barchartsample.Report;
import business.customer.MasterOrderList;
import business.ecosystem.Ecosystem;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.Organization;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author sonalichaudhari
 */
public class OrganisationReportJPanel extends javax.swing.JPanel {

    private MasterOrderList mod;
    private JPanel userProcessContainer;
    private Ecosystem business;
    Report report = new Report();

    public OrganisationReportJPanel(JPanel userProcessContainer, MasterOrderList mod, Ecosystem business) {
        initComponents();
        this.mod = mod;
        this.userProcessContainer = userProcessContainer;
        this.business = business;

        populateNetworkComboBox();

       generateGraph();
    }

//Populating Network Combo Box
    private void populateNetworkComboBox() {
        networkJComboBox.removeAllItems();

        for (Network network : business.getNetworkList()) {
            networkJComboBox.addItem(network);
        }
    }

//PopulatingEnterprise Combo Box   
    private void populateEnterpriseComboBox(Network network) {
        enterpriseJComboBox.removeAllItems();
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            enterpriseJComboBox.addItem(enterprise);

        }

    }
//Graph Generation Method

    public void generateGraph() {

        String organizationName;
        int enterpriseSize = 0;
        int organizationCount = 0;
        int employeeCount = 0;

        DefaultCategoryDataset barchartdata = new DefaultCategoryDataset();

        for (Network network : business.getNetworkList()) {
            if (network.getName().equalsIgnoreCase(networkJComboBox.getSelectedItem().toString())) {
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    if (enterprise.getName().equalsIgnoreCase(enterpriseJComboBox.getSelectedItem().toString())) {
                        organizationCount = enterprise.getOrganizationDirectory().getOrganizationList().size();
                        for (int i = organizationCount; i > 0; i--) {
                            for (Organization organization1 : enterprise.getOrganizationDirectory().getOrganizationList()) {

                                organizationName = organization1.getName();
                                employeeCount = organization1.getEmployeeDirectory().getPersonList().size();
                                barchartdata.setValue(employeeCount, "Organization", organizationName);
                                organizationCount--;
                            }

                        }

                    }

                }
            }
        }

        JFreeChart barchart = ChartFactory.createBarChart("ENTERPRISE", "Types", "Employee Count", barchartdata, PlotOrientation.VERTICAL, true, true, false);
        CategoryPlot p = barchart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.black);
        ChartFrame chartfn = new ChartFrame("Employee Count", barchart, true);

        reportDisplayjPanel.removeAll();
        reportDisplayjPanel.add(chartfn.getChartPanel());
        reportDisplayjPanel.setVisible(true);
        reportDisplayjPanel.validate();
        //this.repaint();
        //  return chartfn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportDisplayjPanel = new javax.swing.JPanel();
        backJButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        enterpriseJComboBox = new javax.swing.JComboBox();
        generateGraphJBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reportDisplayjPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        reportDisplayjPanel.setLayout(new java.awt.BorderLayout());
        add(reportDisplayjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 690, 310));

        backJButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.jpg"))); // NOI18N
        backJButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton7ActionPerformed(evt);
            }
        });
        add(backJButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jLabel1.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        jLabel1.setText("Network");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        networkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkJComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        networkJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBoxActionPerformed(evt);
            }
        });
        add(networkJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 136, -1));

        jLabel3.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        jLabel3.setText("Enterprise");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        enterpriseJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        enterpriseJComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        enterpriseJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseJComboBoxActionPerformed(evt);
            }
        });
        add(enterpriseJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 136, -1));

        generateGraphJBtn.setText("GENERATE GRAPH");
        generateGraphJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateGraphJBtnActionPerformed(evt);
            }
        });
        add(generateGraphJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton7ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton7ActionPerformed

    private void networkJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBoxActionPerformed

        Network network = (Network) networkJComboBox.getSelectedItem();
        if (network != null) {
            populateEnterpriseComboBox(network);
        }
    }//GEN-LAST:event_networkJComboBoxActionPerformed

    private void generateGraphJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateGraphJBtnActionPerformed
        // TODO add your handling code here:
        generateGraph();

    }//GEN-LAST:event_generateGraphJBtnActionPerformed

    private void enterpriseJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseJComboBoxActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_enterpriseJComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton7;
    private javax.swing.JComboBox enterpriseJComboBox;
    private javax.swing.JButton generateGraphJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JPanel reportDisplayjPanel;
    // End of variables declaration//GEN-END:variables

}
