/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.reporting;

import business.barchartsample.Report;
import business.customer.MasterOrderList;
import business.ecosystem.Ecosystem;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author sonalichaudhari
 */
public class RevenueReportJPanel extends javax.swing.JPanel {

    private MasterOrderList mod;
    private JPanel userProcessContainer;
    private Ecosystem business;
    Report report = new Report();

    public RevenueReportJPanel(JPanel userProcessContainer, MasterOrderList mod, Ecosystem business) {
        initComponents();
        this.mod = mod;
        this.userProcessContainer = userProcessContainer;
        this.business = business;

        generateGraph();
    }

    float storeOrderRevenue = 0;
    float customizedRevenue = 0;

    private ChartFrame generateGraph() {
       // setting values for bar graph
        DefaultCategoryDataset barchartdata = new DefaultCategoryDataset();

        barchartdata.setValue(5, "Revenue", "Customized Orders");
        barchartdata.setValue(8, "Revenue", "Orders At Store");

        JFreeChart barchart = ChartFactory.createBarChart("AMOUNT", "CATEGORY", "REVENUE", barchartdata, PlotOrientation.VERTICAL, true, true, false);
        CategoryPlot p = barchart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.black);
        ChartFrame chartfn = new ChartFrame("REVENUE GENERATION", barchart, true);
        // setting display report vlaues
        reportDisplayjPanel.removeAll();
        reportDisplayjPanel.add(chartfn.getChartPanel());
        reportDisplayjPanel.setVisible(true);
        return chartfn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportDisplayjPanel = new javax.swing.JPanel();
        backJButton7 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reportDisplayjPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        reportDisplayjPanel.setLayout(new java.awt.BorderLayout());
        add(reportDisplayjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 690, 310));

        backJButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.jpg"))); // NOI18N
        backJButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton7ActionPerformed(evt);
            }
        });
        add(backJButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton7ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton7;
    private javax.swing.JPanel reportDisplayjPanel;
    // End of variables declaration//GEN-END:variables

}
