/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.customer;

import business.customer.MasterOrderList;
import business.customer.CustomizedOrder;
import business.customer.CustomizedOrderItem;
import business.ecosystem.Ecosystem;
import business.enterprise.CustomerSupportEnterprise;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.CustomerOrganization;
import business.organization.Organization;
import business.organization.StoreOrganization;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sonalichaudhari
 */
public class CustomizeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BuyAtStoreJPanel
     */
    private JPanel userProcessContainer;
    private MasterOrderList mod;
    private CustomerOrganization customerOrganization;
    private UserAccount account;
    private Enterprise enterprise;
    private Ecosystem business;
    private static int count;
    
    public CustomizeJPanel(JPanel userProcessContainer, Organization organization, UserAccount account, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.customerOrganization = (CustomerOrganization) organization;
        this.account = account;
        this.enterprise = enterprise;
        this.business = business;
        customerTextField.setText(account.getUsername());
    }
    CustomizedOrder order = new CustomizedOrder();
    CustomizedOrderItem oi = new CustomizedOrderItem();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        carColorjComboBox = new javax.swing.JComboBox<>();
        carTypejComboBox = new javax.swing.JComboBox();
        engineTypejComboBox = new javax.swing.JComboBox();
        airFilterjComboBox = new javax.swing.JComboBox<>();
        carbodyjComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        wheelTypejComboBox = new javax.swing.JComboBox<>();
        nextJButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        customerTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        batteryjComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        interiorjComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        addJBtn = new javax.swing.JButton();
        fuelTypejComboBox = new javax.swing.JComboBox<>();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(201, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Phosphate", 1, 36)); // NOI18N
        jLabel1.setText(" DESIGN YOUR OWN CAR");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 390, -1));

        jLabel2.setText("Car Type :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 80, 20));

        jLabel3.setText("Engine Type :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        jLabel4.setText("Air Filter :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 80, 20));

        jLabel5.setText("Body:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, 20));

        jLabel6.setText("Color :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));

        carColorjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pearl White", "Black", "Mettalic Grey", "Gold", "Red", "Silver", "Brown" }));
        add(carColorjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 140, -1));

        carTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SUV", "Sedan", "Hatchback" }));
        carTypejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carTypejComboBoxActionPerformed(evt);
            }
        });
        add(carTypejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 140, -1));

        engineTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Diesel V6", "V-8s", "Three 4-cyl. turbos", "Two 2-cyl. turbos" }));
        engineTypejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engineTypejComboBoxActionPerformed(evt);
            }
        });
        add(engineTypejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 140, -1));

        airFilterjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paper", "Foam", "Cotton", "Stainless Steel", "Mesh" }));
        add(airFilterjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 140, 30));

        carbodyjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aluminium", "Magnesium", "Advanced composite materials", "Glass-fibre composites", "Steel", "Light Weight" }));
        add(carbodyjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 140, -1));

        jLabel7.setText("Wheel Type :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        wheelTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alloy ", "Chrome", "Aluminium", "Lead", " " }));
        add(wheelTypejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 140, -1));

        nextJButton.setBackground(new java.awt.Color(204, 204, 255));
        nextJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/next.png"))); // NOI18N
        nextJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextJButtonActionPerformed(evt);
            }
        });
        add(nextJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 70, 50));

        jLabel8.setText("Hello!");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        customerTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        customerTextField.setEnabled(false);
        customerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerTextFieldActionPerformed(evt);
            }
        });
        add(customerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 120, 30));

        jLabel9.setText("Battery Type:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, 20));

        batteryjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lead ", "Nickel Hydride" }));
        add(batteryjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 140, -1));

        jLabel10.setText("Interior Type:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        interiorjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PVC", "Polyurethane", "Ploypropylene" }));
        interiorjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interiorjComboBoxActionPerformed(evt);
            }
        });
        add(interiorjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 140, -1));

        jLabel11.setText("Fuel Type:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        addJBtn.setBackground(new java.awt.Color(102, 102, 255));
        addJBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
        addJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJBtnActionPerformed(evt);
            }
        });
        add(addJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 60, 50));

        fuelTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FFV", "EV", "PHEV", "CNG", "FCV" }));
        fuelTypejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuelTypejComboBoxActionPerformed(evt);
            }
        });
        add(fuelTypejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 140, -1));

        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.jpg"))); // NOI18N
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void nextJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextJButtonActionPerformed
        
        ManageOrderJPanel vjp = new ManageOrderJPanel(userProcessContainer, mod, order, customerOrganization, account, enterprise, business);
        userProcessContainer.add("ManageOrderJPanel", vjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_nextJButtonActionPerformed

    private void engineTypejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engineTypejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_engineTypejComboBoxActionPerformed

    private void interiorjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interiorjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interiorjComboBoxActionPerformed

    private void addJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJBtnActionPerformed
        
        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof CustomerSupportEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof StoreOrganization) {
                            mod = ((StoreOrganization) organization).getMod();
                        }                        
                        
                    }
                }
            }
        }

        // add customised order item to the order
        count++;
        CustomizedOrderItem oi = order.addCustomizedOrderItem();
        order.setCustomer(account.getEmployee());
        order.setOrderNumber(count);
        
        float price = 0;
        oi.getCustomizeProduct().setCarType(carTypejComboBox.getSelectedItem().toString());
        oi.getCustomizeProduct().setEngineType(engineTypejComboBox.getSelectedItem().toString());
        oi.getCustomizeProduct().setAirFilters(airFilterjComboBox.getSelectedItem().toString());
        oi.getCustomizeProduct().setCarBody(carbodyjComboBox.getSelectedItem().toString());
        oi.getCustomizeProduct().setFuelType(fuelTypejComboBox.getSelectedItem().toString());
        oi.getCustomizeProduct().setWheelType(wheelTypejComboBox.getSelectedItem().toString());
        oi.getCustomizeProduct().setCarColor(carColorjComboBox.getSelectedItem().toString());
        oi.getCustomizeProduct().setInteriorType(interiorjComboBox.getSelectedItem().toString());
        oi.getCustomizeProduct().setBatteryType(batteryjComboBox.getSelectedItem().toString());
        
        if (oi.getCustomizeProduct().getCarType().equalsIgnoreCase("Hatchback")) {
            price = price + 1400;
        } else if (oi.getCustomizeProduct().getCarType().equalsIgnoreCase("Sedan")) {
            price = price + 2500;
        } else {
            price = price + 30000;
        }

        //
        if (oi.getCustomizeProduct().getCarType().equalsIgnoreCase("EV")) {
            price = price + 400;
        } else if (oi.getCustomizeProduct().getCarType().equalsIgnoreCase("PHEV")) {
            price = price + 500;
            
        } else if (oi.getCustomizeProduct().getCarType().equalsIgnoreCase("CNG")) {
            price = price + 200;
            
        } else if (oi.getCustomizeProduct().getCarType().equalsIgnoreCase("FCV")) {
            price = price + 300;
            
        }
        //
        
        if (oi.getCustomizeProduct().getEngineType().equalsIgnoreCase("Diesel V6")) {
            price = price + 1000;            
        } else if (oi.getCustomizeProduct().getEngineType().equalsIgnoreCase("V-8s")) {
            price = price + 600;            
        } else if (oi.getCustomizeProduct().getEngineType().equalsIgnoreCase("Three 4-cyl. turbos")) {
            price = price + 500;            
        } else if (oi.getCustomizeProduct().getEngineType().equalsIgnoreCase("Two 2-cyl. turbos")) {
            price = price + 700;            
        }

//   
        if (oi.getCustomizeProduct().getAirFilters().equalsIgnoreCase("Paper")) {
            price = price + 100;
        } else if (oi.getCustomizeProduct().getAirFilters().equalsIgnoreCase("Foam")) {
            price = price + 200;
        } else if (oi.getCustomizeProduct().getAirFilters().equalsIgnoreCase("Cotton")) {
            price = price + 300;
        } else if (oi.getCustomizeProduct().getAirFilters().equalsIgnoreCase("Stainless Steel")) {
            price = price + 400;
        } else if (oi.getCustomizeProduct().getAirFilters().equalsIgnoreCase("Mesh")) {
            price = price + 500;
        }

        //
        if (oi.getCustomizeProduct().getCarBody().equalsIgnoreCase("Aluminium")) {
            price = price + 100;
        } else if (oi.getCustomizeProduct().getCarBody().equalsIgnoreCase("Magnesium")) {
            price = price + 200;
        } else if (oi.getCustomizeProduct().getCarBody().equalsIgnoreCase("Advanced composite materials")) {
            price = price + 300;
        } else if (oi.getCustomizeProduct().getCarBody().equalsIgnoreCase("Glass-fibre composites")) {
            price = price + 400;
        } else if (oi.getCustomizeProduct().getCarBody().equalsIgnoreCase("Steel")) {
            price = price + 500;
        } else if (oi.getCustomizeProduct().getCarBody().equalsIgnoreCase("Light Weight")) {
            price = price + 600;            
        }

//        
        if (oi.getCustomizeProduct().getCarColor().equalsIgnoreCase("Pearl White")) {
            price = price + 100;
        } else if (oi.getCustomizeProduct().getCarColor().equalsIgnoreCase("Black")) {
            price = price + 200;
        } else if (oi.getCustomizeProduct().getCarColor().equalsIgnoreCase("Mettalic Grey")) {
            price = price + 300;
        } else if (oi.getCustomizeProduct().getCarColor().equalsIgnoreCase("Gold")) {
            price = price + 400;
        } else if (oi.getCustomizeProduct().getCarColor().equalsIgnoreCase("Red")) {
            price = price + 500;
        } else if (oi.getCustomizeProduct().getCarColor().equalsIgnoreCase("Silver")) {
            price = price + 600;            
        } else if (oi.getCustomizeProduct().getCarColor().equalsIgnoreCase("Brown")) {
            price = price + 700;            
        }
        //
        if (oi.getCustomizeProduct().getWheelType().equalsIgnoreCase("Alloy")) {
            price = price + 100;
        } else if (oi.getCustomizeProduct().getWheelType().equalsIgnoreCase("Chrome")) {
            price = price + 200;
        } else if (oi.getCustomizeProduct().getWheelType().equalsIgnoreCase("Aluminium")) {
            price = price + 300;
        } else if (oi.getCustomizeProduct().getWheelType().equalsIgnoreCase("Lead")) {
            price = price + 400;
        }
//
        if (oi.getCustomizeProduct().getBatteryType().equalsIgnoreCase("Lead")) {
            price = price + 100;
        } else if (oi.getCustomizeProduct().getWheelType().equalsIgnoreCase("Nickel Hydride")) {
            price = price + 200;
        }
//
        if (oi.getCustomizeProduct().getInteriorType().equalsIgnoreCase("PVC")) {
            price = price + 100;
        } else if (oi.getCustomizeProduct().getInteriorType().equalsIgnoreCase("Polyurethane")) {
            price = price + 200;
        } else if (oi.getCustomizeProduct().getInteriorType().equalsIgnoreCase("Ploypropylene")) {
            price = price + 200;
        }
        
        oi.getCustomizeProduct().setPrice(price);
        JOptionPane.showMessageDialog(null, "Product added!", "Info", JOptionPane.INFORMATION_MESSAGE);

        //addJBtn.setEnabled(false);
    }//GEN-LAST:event_addJBtnActionPerformed

    private void carTypejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carTypejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carTypejComboBoxActionPerformed

    private void fuelTypejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelTypejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuelTypejComboBoxActionPerformed

    private void customerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerTextFieldActionPerformed
        
    }//GEN-LAST:event_customerTextFieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJBtn;
    private javax.swing.JComboBox<String> airFilterjComboBox;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox<String> batteryjComboBox;
    private javax.swing.JComboBox<String> carColorjComboBox;
    private javax.swing.JComboBox carTypejComboBox;
    private javax.swing.JComboBox<String> carbodyjComboBox;
    private javax.swing.JTextField customerTextField;
    private javax.swing.JComboBox engineTypejComboBox;
    private javax.swing.JComboBox<String> fuelTypejComboBox;
    private javax.swing.JComboBox<String> interiorjComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton nextJButton;
    private javax.swing.JComboBox<String> wheelTypejComboBox;
    // End of variables declaration//GEN-END:variables
}
