/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.customer;

import business.customer.MasterOrderList;
import business.customer.CustomizedOrder;
import business.customer.CustomizedOrderItem;
import business.ecosystem.Ecosystem;
import business.enterprise.CustomerSupportEnterprise;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.CustomerOrganization;
import business.organization.Organization;
import business.organization.StoreOrganization;
import business.useraccount.UserAccount;
import business.workqueue.CustomerCustomizedWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sonalichaudhari
 */
public class ManageOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrderJPanel
     */
    private JPanel userProcessContainer;
    private MasterOrderList mod;
    private CustomizedOrder order;
    private CustomerOrganization customerOrganization;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private Ecosystem business;

    public ManageOrderJPanel(JPanel userProcessContainer, MasterOrderList mod, CustomizedOrder order, Organization organization, UserAccount userAccount, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.mod = mod;
        this.order = order;
        this.customerOrganization = (CustomerOrganization) organization;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.business = business;
        customerTextField.setText(userAccount.getUsername());

        populateTable();
    }

    private void populateTable() {

        DefaultTableModel dtm = (DefaultTableModel) customerCartjTable.getModel();
        dtm.setRowCount(0);

        for (CustomizedOrderItem oi : order.getOrderItemList()) {
            Object[] row = new Object[2];
            row[0] = oi;
            row[1] = oi.getCustomizeProduct().getPrice();
            dtm.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerCartjTable = new javax.swing.JTable();
        viewDetailjBtn = new javax.swing.JButton();
        placeOrderjBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        deletejButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        customerTextField = new javax.swing.JTextField();
        refreshJButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(192, 238, 238));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerCartjTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        customerCartjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderItemId", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(customerCartjTable);
        if (customerCartjTable.getColumnModel().getColumnCount() > 0) {
            customerCartjTable.getColumnModel().getColumn(0).setResizable(false);
            customerCartjTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 450, 140));

        viewDetailjBtn.setBackground(new java.awt.Color(102, 153, 255));
        viewDetailjBtn.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        viewDetailjBtn.setText("View Details");
        viewDetailjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailjBtnActionPerformed(evt);
            }
        });
        jPanel1.add(viewDetailjBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 130, 100));

        placeOrderjBtn.setBackground(new java.awt.Color(51, 204, 255));
        placeOrderjBtn.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        placeOrderjBtn.setText("Place Order");
        placeOrderjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderjBtnActionPerformed(evt);
            }
        });
        jPanel1.add(placeOrderjBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 130, 100));

        jLabel1.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 24)); // NOI18N
        jLabel1.setText("Your Cart");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 130, 30));

        deletejButton.setBackground(new java.awt.Color(102, 204, 255));
        deletejButton.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        deletejButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Trash.png"))); // NOI18N
        deletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deletejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 100, 100));

        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.jpg"))); // NOI18N
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 60));

        jLabel8.setText("Hello!");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        customerTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        customerTextField.setEnabled(false);
        customerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(customerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 120, 30));

        refreshJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.png"))); // NOI18N
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 90, 80));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void viewDetailjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailjBtnActionPerformed
        // TODO add your handling code here:

        int selectedRow = customerCartjTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table first to view data", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        CustomizedOrderItem oi = (CustomizedOrderItem) customerCartjTable.getValueAt(selectedRow, 0);
        ViewOrderDetailsJPanel vjp = new ViewOrderDetailsJPanel(userProcessContainer, oi);
        userProcessContainer.add("SupplierWorkAreaJPanel", vjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);


    }//GEN-LAST:event_viewDetailjBtnActionPerformed

    private void placeOrderjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderjBtnActionPerformed

        int selectedRow = customerCartjTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table first to view data", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        mod.addOrderFromInput(order);

        CustomerCustomizedWorkRequest cworkrequest = new CustomerCustomizedWorkRequest();
        cworkrequest.setOrder(order);
        cworkrequest.setStatus("Placed");
        cworkrequest.setCustomerSender(userAccount);
        userAccount.getWorkQueue().getWorkRequestList().add(cworkrequest);

        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof CustomerSupportEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof StoreOrganization) {

                            organization.getWorkQueue().getWorkRequestList().add(cworkrequest);

                        }
                    }
                }
            }
        }
        JOptionPane.showMessageDialog(null, "Order Placed Successfully", "Information!!", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_placeOrderjBtnActionPerformed


    private void deletejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = customerCartjTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table first to delete data", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            CustomizedOrderItem oi = (CustomizedOrderItem) customerCartjTable.getValueAt(selectedRow, 0);
            order.removeOrderItem(oi);
            populateTable();
        }
    }//GEN-LAST:event_deletejButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void customerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerTextFieldActionPerformed

    }//GEN-LAST:event_customerTextFieldActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTable customerCartjTable;
    private javax.swing.JTextField customerTextField;
    private javax.swing.JButton deletejButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton placeOrderjBtn;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton viewDetailjBtn;
    // End of variables declaration//GEN-END:variables
}
